(()=>{'use strict';
const copy={
en:{eyebrow:'INSTITUTIONAL ACCESS',title:'Enter the Amanah workspace.',intro:'Choose the access pathway that matches your role. Your identity is verified by the secure Amanah application; this public site never collects credentials or grants access.',choose:'Choose an access tier',regulator:'Regulator & JAKIM auditor',regulatorSub:'For invited authority and audit accounts',director:'Directorate',directorSub:'For approved governance and executive accounts',enterprise:'Enterprise supply node',enterpriseSub:'For registered manufacturers and operating partners',continue:'Continue to secure sign-in',authNote:'Access is subject to account provisioning, role assignment and applicable authority authorization. Selecting a tier here does not change your permissions.',preview:'INTERACTION PREVIEW',demoTitle:'See how a secure ceremony is presented.',demoIntro:'Preview buttons run a local visual demonstration only. They do not scan biometrics, use a director’s key, attest a production block or establish a session.',demoKeyOne:'Directorate preview key 01',demoKeyTwo:'Directorate preview key 02',demoRun:'Local visual ceremony complete',demoWarning:'DEMO ONLY · No biometric was captured. No credential was checked. No production attestation was made. No account session was created.',boundary:'Formal certification and border-release decisions remain with competent authorities. AI and software assist people; they do not issue those decisions.'},
'zh-Hant':{eyebrow:'機構入口',title:'進入 AMANAH 工作平台。',intro:'請選擇符合您職責的入口。身份驗證由安全的 AMANAH 應用程式處理；此公開網站不會收集登入資料或授予存取權限。',choose:'選擇存取層級',regulator:'監管機構與 JAKIM 稽核員',regulatorSub:'供獲邀的主管機關及稽核帳戶使用',director:'董事會',directorSub:'供已核准的治理及行政帳戶使用',enterprise:'企業供應鏈節點',enterpriseSub:'供已登記的製造商及營運夥伴使用',continue:'前往安全登入',authNote:'存取須視乎帳戶開通、角色分配及主管機關授權。此處選擇層級不會改變您的權限。',preview:'互動預覽',demoTitle:'查看安全驗證流程的呈現方式。',demoIntro:'預覽按鈕僅執行本機視覺示範，不會掃描生物特徵、使用董事密鑰、驗證正式區塊或建立登入工作階段。',demoKeyOne:'董事會預覽密鑰 01',demoKeyTwo:'董事會預覽密鑰 02',demoRun:'本機視覺流程已完成',demoWarning:'僅供示範 · 未擷取生物特徵；未驗證憑證；未進行正式加密證明；未建立任何帳戶工作階段。',boundary:'正式清真認證及邊境放行由具職權的主管機關決定。AI 與軟體提供輔助，不會作出此類決定。'},
ar:{eyebrow:'دخول مؤسسي',title:'الدخول إلى مساحة أمانة.',intro:'اختر مسار الدخول المناسب لدورك. يتم التحقق من الهوية في تطبيق أمانة الآمن؛ هذا الموقع العام لا يجمع بيانات الاعتماد ولا يمنح صلاحية الدخول.',choose:'اختر مستوى الدخول',regulator:'الجهة التنظيمية ومدقق JAKIM',regulatorSub:'لحسابات الجهات والمدققين المدعوين',director:'الإدارة التنفيذية',directorSub:'لحسابات الحوكمة والإدارة المعتمدة',enterprise:'عقدة سلسلة التوريد المؤسسية',enterpriseSub:'للمصنعين والشركاء التشغيليين المسجلين',continue:'المتابعة إلى تسجيل الدخول الآمن',authNote:'يخضع الدخول لتفعيل الحساب وتعيين الدور والتفويض المعمول به. اختيار المستوى هنا لا يغيّر صلاحياتك.',preview:'معاينة تفاعلية',demoTitle:'شاهد طريقة عرض جلسة تحقق آمنة.',demoIntro:'تشغّل أزرار المعاينة عرضاً مرئياً محلياً فقط. لا تمسح البيانات الحيوية ولا تستخدم مفتاحاً تنفيذياً ولا تصادق كتلة إنتاج ولا تنشئ جلسة دخول.',demoKeyOne:'مفتاح معاينة الإدارة 01',demoKeyTwo:'مفتاح معاينة الإدارة 02',demoRun:'اكتمل العرض المحلي',demoWarning:'للعرض فقط · لم تُلتقط بيانات حيوية؛ لم يُفحص اعتماد؛ لم يُنشأ إثبات إنتاج أو جلسة حساب.',boundary:'تظل قرارات الاعتماد الرسمي والإفراج الحدودي من اختصاص الجهات المختصة. يساعد الذكاء الاصطناعي والبرمجيات الأشخاص ولا يصدران تلك القرارات.'}
};
function lang(code){const dict=copy[code]||copy.en;document.documentElement.lang=code==='zh-Hant'?'zh-Hant':code;document.documentElement.dir=code==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(dict[k])el.textContent=dict[k]});document.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===code)));try{localStorage.setItem('ghsc-lang',code)}catch{}}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>lang(b.dataset.lang)));
document.querySelectorAll('[data-role]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-role]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))}));
document.querySelectorAll('[data-demo]').forEach(b=>b.addEventListener('click',async()=>{const stage=document.querySelector('#scanStage'),out=document.querySelector('#demoDigest');stage.dataset.open='true';const msg=(copy[document.documentElement.lang]||copy.en).demoRun;stage.querySelector('[data-i18n="demoRun"]').textContent=msg;const value='GHSC DEMONSTRATION ONLY · directorate preview key '+b.dataset.demo+' · no authentication';try{const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));out.textContent='DEMO DIGEST · SHA-256 · '+[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}catch{out.textContent='DEMO DIGEST · local crypto preview unavailable'};stage.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'})}));
let saved='en';try{saved=localStorage.getItem('ghsc-lang')||'en'}catch{}lang(saved);
})();