import { requireUser } from "@/lib/auth";
import { getPrimaryWorkspace } from "@/lib/workspace";

const steps = [
  ["Authority","authorities"],["Standard / Instrument","instruments"],["Clause / Requirement","requirements"],
  ["Applicability","applicability"],["Control","controls"],["HCP / SCCP","critical_points"],
  ["Evidence","evidence"],["Audit Test","audit_tests"],["Finding","findings"],
  ["Corrective Action","corrective_actions"],["Re-verification","reverifications"],["Authority Gate","authority_gates"],
  ["Trust State","trust_states"],["Operational Release","release_decisions"]
] as const;

export default async function ProcessPage() {
  const { supabase, user } = await requireUser();
  const org = await getPrimaryWorkspace(supabase, user.id);
  if (!org) return <Empty />;
  const countQueries = [
    "ahte_authorities","ahte_instruments","ahte_requirements","ahte_applicability","ahte_controls","ahte_critical_points",
    "ahte_evidence","ahte_audit_tests","ahte_findings","ahte_corrective_actions","ahte_reverifications","ahte_authority_gates",
    "ahte_trust_states","ahte_release_decisions"
  ];
  const counts = await Promise.all(countQueries.map((table) => (supabase as any).from(table).select("id",{count:"exact",head:true}).eq("organization_id",org.id)));
  return <div className="page stack-xl">
    <header><div className="eyebrow">AHTE / CANONICAL PATH</div><h1>End-to-end assurance process</h1><p className="lead">Every stage is separately represented. Undefined transitions remain blocked; authority decisions are never generated by AI.</p></header>
    <section className="card stack">{steps.map(([label],i)=><div className="row-between" key={label}><div><span className="eyebrow">{String(i+1).padStart(2,"0")}</span> <strong>{label}</strong></div><span className="status">{counts[i].count ?? 0} records</span></div>)}</section>
    <section className="card"><strong>Control boundary:</strong> score is descriptive after hard-gates; AHTE operational release is not certification; D5/D6 remain reserved for competent authority/human decision.</section>
  </div>;
}
function Empty(){return <div className="page"><div className="card"><h1>No workspace</h1></div></div>}
