import { cinematicStageImages } from '../scene/sceneImages';
import type { ExceptionEvent, JourneyStage, Scenario } from './types';
export function DigitalTwinCanvas({stage,scenario,exception,tick}:{stage:JourneyStage;scenario:Scenario;exception:ExceptionEvent|null;tick:number}){
  const temperature=exception?.kind==='COLD_CHAIN'?14.2:Number((scenario.temperatureBaseline+Math.sin(tick/3)*.15).toFixed(1));
  const metrics=stage.telemetryData.map(metric=>metric.id==='temperature'?{...metric,value:temperature,status:exception?.kind==='COLD_CHAIN'?'CRITICAL':'OPTIMAL'}:metric.id==='risk'&&exception?{...metric,value:'Contained · critical signal',status:'CRITICAL'}:metric.id==='capa'&&exception?{...metric,value:1,status:'CRITICAL'}:metric.id==='seal'&&exception?.kind==='SEAL_TAMPER'?{...metric,value:'TAMPER_ALERT_OPEN',status:'CRITICAL'}:metric.id==='pcr'&&exception?.kind==='PORCINE_DNA'?{...metric,value:'DETECTED',status:'CRITICAL'}:metric);
  return <section className="platform-panel twin-panel" aria-labelledby="twin-title"><div className="platform-panel-head"><div><p className="eyebrow">{String(stage.stageNumber).padStart(2,'0')} / {stage.governanceType.replaceAll('_',' ')}</p><h3 id="twin-title">{stage.title}</h3></div><span className={exception?'platform-status held':'platform-status'}>{exception?'D4 · CONTAINED':stage.decisionLevel.split('_')[0]+' · '+(stage.governanceType==='HUMAN_SOVEREIGN'?'HUMAN RECORD':'CONNECTED')}</span></div>
    <p className="platform-stage-summary">{stage.summary}</p>
    <div className="platform-twin" data-kind={stage.kind} data-held={Boolean(exception)}><div className="platform-cinematic-frame"><img key={stage.id} className="platform-cinematic-image" src={`assets/${cinematicStageImages[stage.stageNumber-1]}`} alt={`${stage.title}: cinematic view of ${stage.location}`} decoding="async" /><div className="platform-cinematic-caption"><span>{String(stage.stageNumber).padStart(2,'0')} / {stage.subtitle}</span>{exception?<strong>ONWARD ALLOCATION BLOCKED</strong>:null}</div></div><div className="twin-object"><span>{scenario.batch}</span><span>{stage.location}</span></div></div>
    <dl className="platform-metrics" aria-label="Stage telemetry">{metrics.map(metric=><div key={metric.id} data-status={metric.status}><dt>{metric.label}</dt><dd>{metric.value} {metric.unit}<small>{metric.status}</small></dd></div>)}</dl>
    <div className="platform-operator"><span>Accountable actor</span><strong>{stage.actor}</strong></div>
  </section>;
}
