import type { EngineAction } from './stageEngine';
import type { DecisionLevel, PlatformState, Scenario } from './types';
const levels:[DecisionLevel,string,string][]=[['D0_AUTO','Signals','Automated checks'],['D1_RULE','Rules','Applicable requirements'],['D2_AI_CHECK','AI checks','Checklist assistance'],['D3_AI_RECOMMEND','Advice','Human review'],['D4_AUTO_HOLD','Containment','Configured quarantine'],['D5_HUMAN_CERT','Certification','Competent authority'],['D6_SOVEREIGN_RELEASE','Release','Sovereign / authorised human']];
export function GovernanceMatrix({level,state,scenario,dispatch}:{level:DecisionLevel;state:PlatformState;scenario:Scenario;dispatch:(action:EngineAction)=>void}){
  const exception=state.activeException;const active=exception?'D4_AUTO_HOLD':level;
  const phaseLabels={HOLD:'Record investigation',INVESTIGATION:'Record corrective action',CORRECTIVE_ACTION:'Record re-verification',REVERIFICATION:'Close operating hold'};
  return <section className="platform-panel governance-panel" aria-labelledby="governance-title"><div className="platform-panel-head"><h3 id="governance-title">Decisions & response</h3><span className="platform-status">D0–D6</span></div>
    <div className="platform-governance" aria-label="Stage decision level">{levels.map(([code,title,owner])=><article key={code} data-level={code} aria-current={active===code?'step':undefined}><strong>{code.split('_')[0]}</strong><span>{title}</span><small>{owner}</small></article>)}</div>
    <p className="platform-boundary">AI assists. Humans and competent authorities decide. D5/D6 records retain their source owners.</p>
    <div className="platform-exception-triggers" role="group" aria-label="Operating scenarios"><button disabled={Boolean(exception)} type="button" onClick={()=>dispatch({type:'INJECT',kind:'COLD_CHAIN'})}>Cold-chain breach · 14.2 °C</button><button disabled={Boolean(exception)} type="button" onClick={()=>dispatch({type:'INJECT',kind:'SEAL_TAMPER'})}>Seal tamper</button><button disabled={Boolean(exception)} type="button" onClick={()=>dispatch({type:'INJECT',kind:'PORCINE_DNA'})}>Porcine DNA non-conformance</button></div>
    {exception?<div className="platform-incident" role="region" aria-label="Affected lots and corrective action"><p className="eyebrow">D4 · {exception.phase.replaceAll('_',' ')}</p><h4>{exception.title}</h4><dl><div><dt>Observed</dt><dd>{exception.observedValue}</dd></div><div><dt>Required threshold</dt><dd>{exception.thresholdValue}</dd></div></dl><p>{exception.capaAction}</p>
      <h4>Affected product lineage</h4><p className="platform-sku">{scenario.sku}</p><ol className="platform-recall-tree"><li><strong>Source · {scenario.batch}</strong><span>Shipment {scenario.shipment} · container {scenario.container} · seal {scenario.seal}</span><ol>{scenario.allocations.map(allocation=><li key={allocation.batch}><strong>{allocation.batch} → {allocation.lot}</strong><span>{allocation.distributor} → {allocation.store} → {allocation.order} · {allocation.cases} cases</span></li>)}</ol></li></ol><p>Unaffected source batch: <strong>{scenario.unaffectedBatch}</strong>. Its operating status stays separate.</p>
      <button type="button" disabled={state.stageLogs.some(event=>event.event==='RECALL_PROPAGATED'&&event.payload.exceptionId===exception.id)} onClick={()=>dispatch({type:'RECALL'})}>Record downstream recall</button>
      {exception.phase==='REVERIFICATION'?<label className="platform-review"><input type="checkbox" checked={state.evidenceConfirmed} onChange={event=>dispatch({type:'CONFIRM',confirmed:event.target.checked})}/><span>Confirm corrective evidence, repeat checks and reviewer record</span></label>:null}
      <button type="button" className="platform-response-action" disabled={exception.phase==='REVERIFICATION'&&!state.evidenceConfirmed} onClick={()=>dispatch({type:exception.phase==='REVERIFICATION'?'RESOLVE':'NEXT_PHASE'})}>{phaseLabels[exception.phase]}</button>
    </div>:state.resolution?<p className="platform-resolution" role="status">{state.resolution}</p>:<p className="platform-resolution">Choose an event to follow containment through investigation, corrective action and reviewed re-verification.</p>}
  </section>;
}
