import { useStageEngine } from './useStageEngine';
import { DigitalTwinCanvas } from './DigitalTwinCanvas';
import { LedgerTerminal } from './LedgerTerminal';
import { GovernanceMatrix } from './GovernanceMatrix';
import '../../styles/operating-platform.css';
export default function OperatingPlatform(){
  const {state,dispatch,stages,currentStage,scenario,proofs,proofError}=useStageEngine();const held=Boolean(state.activeException);const duration=5000/state.playbackSpeed;
  return <div className="operating-platform" data-playback={state.playbackMode}>
    <div className="platform-heading"><div><p className="eyebrow">AMANAH / CONNECTED OPERATING PLATFORM</p><h3>One product. A complete operating loop.</h3><p>Interactive scenario · {scenario.origin} → {scenario.destination}. Explore live readings, evidence and accountable response around the same SKU and source batch.</p></div><a href="index.html#journey">Documentary journey ↗</a></div>
    <div className="platform-identity"><span><small>PRODUCT</small>{scenario.product}</span><span><small>SKU</small>{scenario.sku}</span><span><small>SOURCE BATCH</small>{scenario.batch}</span></div>
    <div className="platform-controls" role="group" aria-label="Operating platform playback"><button type="button" disabled={held||state.currentStageIndex===0} onClick={()=>dispatch({type:'SELECT',index:state.currentStageIndex-1})}>Previous</button><button type="button" disabled={held} onClick={()=>dispatch({type:state.playbackMode==='AUTONOMOUS_PLAY'?'PAUSE':'PLAY'})}>{state.playbackMode==='AUTONOMOUS_PLAY'?'Pause operating journey':'Play operating journey'}</button><button type="button" disabled={held||state.currentStageIndex===stages.length-1} onClick={()=>dispatch({type:'SELECT',index:state.currentStageIndex+1})}>Next</button><button type="button" disabled={held} onClick={()=>dispatch({type:'RESTART'})}>Restart operating journey</button><div role="group" aria-label="Operating playback speed">{([1,2,4] as const).map(speed=><button type="button" key={speed} disabled={held} aria-pressed={state.playbackSpeed===speed} onClick={()=>dispatch({type:'SPEED',speed})}>{speed}×</button>)}</div><div className="platform-countdown"><progress value={state.elapsed} max={duration} aria-label="Time to next operating stage"/><span>{held?'Held for accountable response':state.playbackMode==='AUTONOMOUS_PLAY'?`${((duration-state.elapsed)/1000).toFixed(1)}s to next stage`:'Paused for inspection'}</span></div></div>
    <nav className="platform-stepper" aria-label="Twelve operating stages">{stages.map((stage,index)=><button key={stage.id} type="button" disabled={held} aria-current={index===state.currentStageIndex?'step':undefined} aria-pressed={index===state.currentStageIndex} data-reached={index<state.currentStageIndex} onClick={()=>dispatch({type:'SELECT',index})}><span>{String(stage.stageNumber).padStart(2,'0')}</span>{stage.title}</button>)}</nav>
    <div className="platform-dashboard"><DigitalTwinCanvas stage={currentStage} scenario={scenario} exception={state.activeException} tick={Math.floor(state.virtualTime/1000)}/><div className="platform-evidence-column"><LedgerTerminal stage={currentStage} proofs={proofs} error={proofError} pending={proofs.length!==state.stageLogs.length}/><GovernanceMatrix level={currentStage.decisionLevel} state={state} scenario={scenario} dispatch={dispatch}/></div></div>
    <div className="platform-consumer"><div><p className="eyebrow">THE CONSUMER VIEW</p><h4>{scenario.product}</h4><p>{scenario.sku} · source batch {scenario.batch}</p><p>{state.activeException?'An operating hold affects the connected lots. Receiving, distribution and sale remain contained pending reviewed disposition.':'Origin, audit session, sample, custody and receiving records are connected to this product. Select any stage to inspect its evidence.'}</p></div><div><span>Origin · {scenario.origin}</span><span>Audit · {scenario.audit}</span><span>Sample · {scenario.sample}</span><span>Destination lot · {scenario.importerLot}</span><a href="verify.html">Verify an issuer-authorised disclosure ↗</a></div></div>
  </div>;
}
