import rawScenario from '../../../../ghscl-website/fixtures/operating-scenario.json';
import type { JourneyStage, Scenario, TelemetryMetric } from './types';
export const scenario: Scenario = rawScenario;
const metric = (id: string, label: string, value: string | number, unit?: string): TelemetryMetric => ({ id, label, value, unit, status: 'OPTIMAL' });
type Definition = Pick<JourneyStage, 'title' | 'subtitle' | 'actor' | 'location' | 'decisionLevel' | 'summary' | 'telemetryData' | 'standardsInScope' | 'kind'>;
const definitions: Definition[] = [
  { title:'Origin identity', subtitle:'The product enters with a stable identity', actor:'Manufacturer / quality team', location:scenario.origin, decisionLevel:'D0_AUTO', kind:'factory', summary:'Bind the legal entity, formulation, facility, SKU and source batch before the first handoff.', telemetryData:[metric('batch','Source batch',scenario.batch),metric('sku','SKU',scenario.sku),metric('facility','Facility',scenario.facility)], standardsInScope:['MS 1500:2019','MHMS 2020'] },
  { title:'Smart-glasses audit', subtitle:'Human observations, assisted by AI', actor:'Assigned auditor + checklist assistant', location:'Foshan production line 4', decisionLevel:'D2_AI_CHECK', kind:'audit', summary:'Inspect controls, capture evidence and assess findings. AI matches the checklist; the auditor owns the conclusion and signed session.', telemetryData:[metric('session','Audit session',scenario.audit),metric('match','Checklist match',99.4,'%'),metric('review','Reviewer','Human auditor')], standardsInScope:['MS 1500:2019','MHMS 2020','MS 2691:2021'] },
  { title:'Hengqin laboratory', subtitle:'The sample remains bound to the batch', actor:scenario.laboratory, location:'Hengqin, Zhuhai', decisionLevel:'D1_RULE', kind:'lab', summary:'Follow seal, custody, accession, method, quality controls, technical review and report binding. The sample result supports the assurance dossier.', telemetryData:[metric('sample','Sample',scenario.sample),metric('pcr','Porcine DNA result','NOT_DETECTED'),metric('qc','QC review','Completed in scenario')], standardsInScope:['MS 2627:2017','Applicable method and laboratory scope'] },
  { title:'Standards & authority', subtitle:'Evidence maps to applicable obligations', actor:'Assurance reviewer / competent authority', location:'AHTE ⇄ Direct JAKIM API ⇄ JAKIM', decisionLevel:'D5_HUMAN_CERT', kind:'standards', summary:'Map product, premises and destination requirements to controls and evidence. The D5 certification record is owned by the competent authority; the engine views that record.', telemetryData:[metric('dossier','Dossier','DOSSIER-0891'),metric('controls','Mapped controls',18),metric('authority','Certification owner','D5 · competent authority')], standardsInScope:['MS 1500:2019','MS 1900:2025','MPPHM 2020','MHMS 2020'] },
  { title:'Warehouse twin', subtitle:'Condition and segregation follow the lot', actor:'Origin warehouse operator', location:'Shenzhen cold-chain hub · Bay C04', decisionLevel:'D0_AUTO', kind:'warehouse', summary:'Inspect receiving, quarantine, segregated storage and dispatch readiness. Link the storage bay and temperature history to the source batch.', telemetryData:[metric('temperature','Temperature',scenario.temperatureBaseline,'°C'),metric('zone','Storage zone','C04 · segregated'),metric('inventory','Cases',1200)], standardsInScope:['MS 2400-2:2019'] },
  { title:'Sinotrans custody', subtitle:'The operator records the physical handoff', actor:'Sinotrans / logistics operator', location:'Nansha-bound freight route', decisionLevel:'D0_AUTO', kind:'logistics', summary:'Bind vehicle, container, electronic seal and custody transfer to the shipment. Condition and route events travel with the same product record.', telemetryData:[metric('container','Container',scenario.container),metric('seal','Electronic seal',scenario.seal),metric('temperature','Cargo temperature',scenario.temperatureBaseline,'°C')], standardsInScope:['MS 2400-1:2019'] },
  { title:'Export customs', subtitle:'Border release has its own owner', actor:'China export authority / port operator', location:scenario.exportPort, decisionLevel:'D6_SOVEREIGN_RELEASE', kind:'port', summary:'Reconcile bill of lading, container, seal and inspection records. The walkthrough displays an authority-owned export disposition; it does not execute one.', telemetryData:[metric('bol','Bill of lading','BOL-CN-0891'),metric('seal','Seal reconciliation','INTACT'),metric('release','Export disposition','Recorded human decision')], standardsInScope:['Applicable China export and customs requirements'] },
  { title:'China → GCC transit', subtitle:'Direct movement, continuous evidence', actor:'Carrier / Command Center', location:'South China Sea → Indian Ocean', decisionLevel:'D0_AUTO', kind:'transit', summary:'Correlate route, geofence, temperature and seal events across the direct China-to-GCC corridor. Malaysia remains the governance plane.', telemetryData:[metric('temperature','Cargo temperature',scenario.temperatureBaseline,'°C'),metric('position','Position','8.40° N · 77.10° E'),metric('geofence','Route status','Within corridor')], standardsInScope:['MS 2400-1:2019','Applicable carrier controls'] },
  { title:'GCC port inspection', subtitle:'Arrival and import disposition stay distinct', actor:'GCC port / customs authority', location:scenario.destinationPort, decisionLevel:'D6_SOVEREIGN_RELEASE', kind:'port', summary:'Inspect pre-arrival documents, container and seal. Keep import disposition, certification status and operator receiving acceptance as separate records.', telemetryData:[metric('dossier','Arrival dossier','Reconciled'),metric('container','Container',scenario.container),metric('release','Import disposition','Recorded human decision')], standardsInScope:['Applicable UAE/GCC import requirements'] },
  { title:'Command Center', subtitle:'Detect, contain, investigate and re-verify', actor:'GHSCL Command Center', location:'Regional operations hub', decisionLevel:'D3_AI_RECOMMEND', kind:'monitoring', summary:'Watch linked signals, assess changing risk and recommend preemptive action. A breach activates D4 containment; investigation and corrective evidence govern the next operating status.', telemetryData:[metric('signals','Connected event streams',6),metric('risk','Risk trend','Stable'),metric('capa','Open corrective actions',0)], standardsInScope:['Applicable controls','Incident and corrective-action procedure'] },
  { title:'GCC receiving & retail', subtitle:'One batch becomes accountable allocations', actor:'Importer → distributor → retailer', location:scenario.destination, decisionLevel:'D0_AUTO', kind:'retail', summary:'Reconcile purchase order, ASN and receiving lot; allocate 1,200 cases across two downstream lots. Each store and order retains the source lineage for withdrawal and recall.', telemetryData:[metric('lot','Receiving lot',scenario.importerLot),metric('asn','ASN',scenario.asn),metric('allocation','Cases allocated',1200)], standardsInScope:['MS 2400-2:2019','MS 2400-3:2019','Destination receiving requirements'] },
  { title:'Consumer provenance', subtitle:'The product story closes the loop', actor:'Buyer / consumer / Command Center', location:'GCC retail point of sale', decisionLevel:'D0_AUTO', kind:'consumer', summary:'Inspect permitted product, batch, audit, laboratory and custody context. Post-market signals remain connected to the same source and affected downstream allocations.', telemetryData:[metric('sku','Product SKU',scenario.sku),metric('batch','Source batch',scenario.batch),metric('history','Connected stages',12)], standardsInScope:['Purpose-bound issuer disclosure policy'] }
];
export const initialStagesData: JourneyStage[] = definitions.map((stage,index)=>({
  ...stage,id:`stage-${index+1}`,stageNumber:index+1,
  governanceType:stage.decisionLevel==='D6_SOVEREIGN_RELEASE'||stage.decisionLevel==='D5_HUMAN_CERT'?'HUMAN_SOVEREIGN':stage.decisionLevel==='D2_AI_CHECK'||stage.decisionLevel==='D3_AI_RECOMMEND'?'AI_ASSISTED':'AUTOMATED_IOT',
  operatorSignature:`Scenario operator record · ${stage.actor}`,
  rawJsonLog:{environment:scenario.environment,scenarioId:scenario.id,stageId:`stage-${index+1}`,product:scenario.product,sku:scenario.sku,batch:scenario.batch,shipment:scenario.shipment,container:scenario.container,seal:scenario.seal,sourceOwner:stage.actor,decisionLevel:stage.decisionLevel,authorityActionExecuted:false}
}));
