-- AHTE / IQ300 trust-platform foundation.
-- Mirrors the live 0008 migration applied to Supabase project lqvyyylrydcpjochknag.
-- Source architecture: GlobalHalalDigitalTrust main, IQ300 doctrine v3.1 and schema/path registries.
create extension if not exists pgcrypto;

create table if not exists public.ahte_authorities (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, code text not null, name text not null, jurisdiction text, authority_type text not null default 'competent_authority', status text not null default 'active' check(status in('active','inactive','pending')), source_reference text, source_status text not null default 'unverified' check(source_status in('verified','unverified','conflicted')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,code));
create table if not exists public.ahte_instruments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, authority_id uuid references public.ahte_authorities(id) on delete set null, code text not null, title text not null, instrument_type text not null default 'standard', version text, jurisdiction text, source_status text not null default 'active' check(source_status in('verified','active','unverified','conflicted')), source_reference text, effective_from date, effective_to date, supersedes_id uuid references public.ahte_instruments(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,code,version));
create table if not exists public.ahte_requirements (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, instrument_id uuid not null references public.ahte_instruments(id) on delete cascade, locator text not null, title text, requirement_text text, source_status text not null default 'active' check(source_status in('verified','active','unverified','conflicted')), applicability_rule text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(instrument_id,locator));
create table if not exists public.ahte_applicability (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, requirement_id uuid not null references public.ahte_requirements(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, shipment_id uuid, decision text not null check(decision in('applicable','not_applicable','conditional','pending')), rationale text, decided_by uuid references auth.users(id), decided_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.ahte_controls (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, requirement_id uuid references public.ahte_requirements(id) on delete set null, project_id uuid references public.projects(id) on delete cascade, code text not null, name text not null, description text, owner_user_id uuid references auth.users(id), status text not null default 'planned' check(status in('planned','implemented','verified','failed','retired')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,code));
create table if not exists public.ahte_critical_points (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, control_id uuid not null references public.ahte_controls(id) on delete cascade, point_type text not null check(point_type in('hcp','sccp')), process_step text not null, hazard text, control_measure text, monitoring_method text, escalation_rule text, created_at timestamptz not null default now());
create table if not exists public.ahte_evidence (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, control_id uuid references public.ahte_controls(id) on delete set null, evidence_class text not null check(evidence_class in('E1','E2','E3','E4','E5')), title text not null, evidence_type text not null, source_uri text, content_hash text, collected_at timestamptz, valid_from timestamptz, valid_to timestamptz, status text not null default 'unverified' check(status in('unverified','verified','expired','contested','rejected')), metadata jsonb not null default '{}'::jsonb, created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.ahte_audit_tests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, control_id uuid references public.ahte_controls(id) on delete set null, evidence_id uuid references public.ahte_evidence(id) on delete set null, test_code text not null, method text not null, tester_user_id uuid references auth.users(id), result text not null default 'pending' check(result in('pending','conforming','non_conforming','observation','not_tested')), tested_at timestamptz, notes text, created_at timestamptz not null default now(), unique(organization_id,test_code));
create table if not exists public.ahte_findings (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, audit_test_id uuid references public.ahte_audit_tests(id) on delete set null, control_id uuid references public.ahte_controls(id) on delete set null, finding_code text not null, severity text not null default 'medium' check(severity in('low','medium','high','critical')), description text not null, status text not null default 'open' check(status in('open','accepted','corrective_action','verified','closed')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,finding_code));
create table if not exists public.ahte_corrective_actions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, finding_id uuid not null references public.ahte_findings(id) on delete cascade, owner_user_id uuid references auth.users(id), root_cause text, action_plan text not null, due_date date, status text not null default 'open' check(status in('open','in_progress','submitted','verified','rejected','closed')), verification_notes text, verified_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.ahte_reverifications (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, corrective_action_id uuid not null references public.ahte_corrective_actions(id) on delete cascade, result text not null check(result in('pending','passed','failed')), tester_user_id uuid references auth.users(id), tested_at timestamptz, evidence_id uuid references public.ahte_evidence(id) on delete set null, notes text, created_at timestamptz not null default now());
create table if not exists public.ahte_authority_gates (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, authority_id uuid references public.ahte_authorities(id) on delete set null, gate_code text not null, gate_type text not null, status text not null default 'open' check(status in('open','pending','passed','failed','expired','contested')), decision_reference text, decision_date date, decided_by uuid references auth.users(id), rationale text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,gate_code));
create table if not exists public.ahte_trust_states (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, entity_type text not null, entity_id uuid not null, state text not null check(state in('unverified','verified','conditionally_verified','expired','contested','held','released','rejected')), hard_gate_status text not null default 'open', score numeric(6,3), vector jsonb not null default '{}'::jsonb, rationale text, effective_at timestamptz not null default now(), expires_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.ahte_assessments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, subject_type text not null, subject_id uuid not null, model_name text, model_version text, assessment text not null, confidence numeric(6,5), evidence_ids uuid[] not null default '{}', status text not null default 'advisory' check(status='advisory'), created_at timestamptz not null default now());
create table if not exists public.ahte_hitm_cases (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, assessment_id uuid references public.ahte_assessments(id) on delete set null, decision_class text not null, status text not null default 'open' check(status in('open','under_review','decided','closed')), assigned_to uuid references auth.users(id), question text not null, evidence_ids uuid[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.ahte_authority_decisions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, authority_gate_id uuid references public.ahte_authority_gates(id) on delete set null, hitm_case_id uuid references public.ahte_hitm_cases(id) on delete set null, decision text not null, decision_reference text, signed_by uuid references auth.users(id), signature_hash text, decided_at timestamptz, status text not null default 'draft' check(status in('draft','signed','revoked')), created_at timestamptz not null default now());
create table if not exists public.ahte_ai_provenance (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, assessment_id uuid references public.ahte_assessments(id) on delete cascade, provider text, model_name text, model_version text, prompt_hash text, input_hash text, output_hash text, created_at timestamptz not null default now());
create table if not exists public.ahte_trust_vectors (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, entity_type text not null, entity_id uuid not null, dimensions jsonb not null default '{}'::jsonb, score numeric(6,3), methodology_version text, calculated_at timestamptz not null default now());
create table if not exists public.ahte_release_decisions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, trust_state_id uuid references public.ahte_trust_states(id) on delete set null, decision text not null check(decision in('hold','release','release_with_conditions','revoke')), reason text not null, decided_by uuid references auth.users(id), decided_at timestamptz not null default now(), conditions jsonb not null default '{}'::jsonb, unique(organization_id,project_id));
create table if not exists public.ahte_fracture_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, entity_type text not null, entity_id uuid not null, fracture_type text not null, severity text not null default 'high' check(severity in('medium','high','critical')), detected_at timestamptz not null default now(), auto_hold boolean not null default true, resolution text, resolved_at timestamptz, resolved_by uuid references auth.users(id));
create table if not exists public.ahte_trust_packets (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, packet_type text not null, schema_version text not null, identity_object jsonb not null, certificate_object jsonb, evidence_object jsonb not null, custody_object jsonb, audit_object jsonb, authority_gate_object jsonb, trust_state_object jsonb, port_custody_object jsonb, content_hash text, status text not null default 'draft' check(status in('draft','validated','issued','revoked')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.ahte_identities (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, entity_type text not null, legal_name text not null, registration_no text, jurisdiction text, verification_status text not null default 'unverified' check(verification_status in('unverified','verified','expired','contested')), verified_at timestamptz, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.ahte_certificates (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, identity_id uuid references public.ahte_identities(id) on delete set null, authority_id uuid references public.ahte_authorities(id) on delete set null, certificate_no text, scope text, issued_on date, expires_on date, status text not null default 'unverified' check(status in('unverified','verified','expired','suspended','revoked','contested')), source_evidence_id uuid references public.ahte_evidence(id) on delete set null, created_at timestamptz not null default now());
create table if not exists public.ahte_custody_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, entity_type text not null, entity_id uuid not null, event_type text not null, location text, occurred_at timestamptz not null, actor_identity_id uuid references public.ahte_identities(id) on delete set null, evidence_id uuid references public.ahte_evidence(id) on delete set null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.ahte_port_custody_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, port_code text not null, event_type text not null, status text not null default 'pending', occurred_at timestamptz, authority_reference text, evidence_id uuid references public.ahte_evidence(id) on delete set null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.ahte_standard_mappings (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, instrument_id uuid not null references public.ahte_instruments(id) on delete cascade, requirement_id uuid references public.ahte_requirements(id) on delete cascade, control_id uuid references public.ahte_controls(id) on delete cascade, mapping_status text not null default 'draft' check(mapping_status in('draft','reviewed','approved','active')), notes text, created_at timestamptz not null default now());
create table if not exists public.ahte_partners (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null, partner_type text not null, role text, authority_status text not null default 'unverified' check(authority_status in('unverified','verified','conflicted')), identity_id uuid references public.ahte_identities(id) on delete set null, notes text, created_at timestamptz not null default now());
create table if not exists public.ahte_laboratories (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, partner_id uuid references public.ahte_partners(id) on delete set null, name text not null, accreditation_status text not null default 'unverified', accreditation_scope text, method_scope text, acceptance_status text not null default 'pending', created_at timestamptz not null default now());
create table if not exists public.ahte_shipments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, shipment_code text not null, corridor text not null default 'China → GCC direct', origin_country text, destination_market text, importer text, exporter text, status text not null default 'not_instantiated' check(status in('not_instantiated','screening','qualified','booked','in_transit','border_hold','released','received','closed','rejected')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,shipment_code));
create table if not exists public.ahte_shipment_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, shipment_id uuid not null references public.ahte_shipments(id) on delete cascade, identity_id uuid references public.ahte_identities(id) on delete set null, certificate_id uuid references public.ahte_certificates(id) on delete set null, sku text not null, batch_no text, quantity numeric, unit text, eligibility_status text not null default 'pending' check(eligibility_status in('pending','eligible','ineligible','held')), created_at timestamptz not null default now());

create index if not exists ahte_requirements_instrument_idx on public.ahte_requirements(instrument_id);
create index if not exists ahte_controls_requirement_idx on public.ahte_controls(requirement_id);
create index if not exists ahte_evidence_project_idx on public.ahte_evidence(organization_id,project_id,evidence_class,status);
create index if not exists ahte_findings_status_idx on public.ahte_findings(organization_id,status,severity);
create index if not exists ahte_gates_status_idx on public.ahte_authority_gates(organization_id,status);
create index if not exists ahte_trust_state_entity_idx on public.ahte_trust_states(organization_id,entity_type,entity_id);
create index if not exists ahte_shipments_status_idx on public.ahte_shipments(organization_id,status);
create index if not exists ahte_custody_entity_idx on public.ahte_custody_events(organization_id,entity_type,entity_id,occurred_at desc);

create or replace function public.ahte_set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
do $$ declare t text; begin foreach t in array array['ahte_authorities','ahte_instruments','ahte_requirements','ahte_controls','ahte_findings','ahte_corrective_actions','ahte_authority_gates','ahte_hitm_cases','ahte_trust_packets','ahte_shipments'] loop execute format('drop trigger if exists %I on public.%I',t||'_updated_at',t); execute format('create trigger %I before update on public.%I for each row execute procedure public.ahte_set_updated_at()',t||'_updated_at',t); end loop; end $$;

do $$ declare t text; begin foreach t in array array['ahte_authorities','ahte_instruments','ahte_requirements','ahte_applicability','ahte_controls','ahte_critical_points','ahte_evidence','ahte_audit_tests','ahte_findings','ahte_corrective_actions','ahte_reverifications','ahte_authority_gates','ahte_trust_states','ahte_assessments','ahte_hitm_cases','ahte_authority_decisions','ahte_ai_provenance','ahte_trust_vectors','ahte_release_decisions','ahte_fracture_events','ahte_trust_packets','ahte_identities','ahte_certificates','ahte_custody_events','ahte_port_custody_events','ahte_standard_mappings','ahte_partners','ahte_laboratories','ahte_shipments','ahte_shipment_items'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists %I on public.%I',t||'_org_access',t); execute format('create policy %I on public.%I for all to authenticated using (exists(select 1 from public.organization_members m where m.organization_id=%I.organization_id and m.user_id=(select auth.uid()))) with check (exists(select 1 from public.organization_members m where m.organization_id=%I.organization_id and m.user_id=(select auth.uid())))',t||'_org_access',t,t,t); end loop; end $$;

grant select,insert,update,delete on all tables in schema public to authenticated;
